framework:
  messenger:
    default_bus: messenger.bus.default

    transports:
      inbox:
        dsn: 'doctrine://default?queue_name=inbox'
      async:
        dsn: '%env(MESSENGER_TRANSPORT_AMQP_DSN)%'

    routing:
      'App\Message\*': inbox
