services:
  php:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      UMASK: "0000"
      XDEBUG_MODE: "debug"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"

  amqp:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - default

  pact-mock-server:
    image: pactfoundation/pact-cli:latest
    command:
      [
        "pact-mock-service",
        "-p", "7200",
        "-h", "0.0.0.0",
        "--pact-dir", "/pacts",
        "--consumer", "AuthorsConsumer",
        "--provider", "AuthorsApi"
      ]
    ports:
      - "7200:7200"
    volumes:
      - ./tests/Pact/pacts:/pacts
